### ISSUE TITLE
Enabled visualization does not show up in notebooks

### ISSUE THREAD

**Issue by gkohnen** [volumeint/helium-volume-leaflet#4]
Hello,
just installed the 0.8.0 snapshot of Zeppelin with Helium, and enabled volume-leaflet on the Helium page. Even though I load geospatial data successfully in a notebook, I don't see a visualization button enabling me to display the volume-leaflet visualization.
This is running on Ubuntu 14.04 in a VM accordingly to the default instructions for installing Zeppelin 0.8.0. I also tried two browsers (Chrome, Firefox) to no avail.
Regards,
Georges

**Comment by volumeint** [comment]
I've noticed that the browser likes to cache the javascript that generates those buttons.  I've had to hit ctrl-F5 in firefox to force the browser to reload the notebook page to get newly installed helium module buttons to show up.

**Comment by gkohnen** [comment]
Hi,
thanks for your answer! unfortunately, that does not work either. Seems to
be a specific helium issue on zeppelin version 0.8.0, I've opened a ticket
on the Zeppelin project page.
regards,
Georges

**Comment by gkohnen** [comment]
Issue solved in Zeppelin - closing issue here.
https://github.com/apache/zeppelin/pull/2421
https://issues.apache.org/jira/browse/ZEPPELIN-2656
Georges
